In [30]:
import pandas as pd
import numpy as np
import openpyxl
import os
import glob

In [31]:
dir = "../../Data/Processed Data/test_read"

dfs = []
filenames = []

for file in glob.glob(os.path.join(dir, "*.xlsx")):
    df = pd.read_excel(file)
    dfs.append(df)
    #removing the extension from the filename
    filenames.append(os.path.basename(file).split(".")[0])

In [32]:
dfs[0].head()

         Date  Affected  T2MDEW    T2M   RH2M  WS10M
0  2019/09/01         0   27.05  29.83  85.75   1.33
1  2019/09/02         0   26.58  28.70  88.69   3.20
2  2019/09/03         0   26.75  28.62  89.88   4.31
3  2019/09/04         0   26.90  28.28  92.31   3.69
4  2019/09/05         0   26.62  28.19  91.31   4.05

In [33]:
#print the unique shapes of the dataframes 
print(set([df.shape for df in dfs]))

{(720, 6), (553, 6)}

In [34]:
# includinf all the dataframes, find out how many common date values are there in the dataframes
common_dates = set(dfs[0].Date)
for df in dfs[1:]:
    common_dates = common_dates.intersection(df.Date)

print(len(common_dates))

553

In [35]:
#filter the dataframes to only include the common dates
for i, df in enumerate(dfs):
    dfs[i] = df[df.Date.isin(common_dates)]

In [36]:
#print the unique shapes of the dataframes 
print(set([df.shape for df in dfs]))

{(553, 6)}

In [37]:
dir = "../../Data/Processed Data/test_write"

#write the dataframes to excel files with the same filenames
for i, df in enumerate(dfs):
    df.to_excel(os.path.join(dir, filenames[i] + ".xlsx"), index=False)
    print(filenames[i] + ".xlsx is written")

250 shojja.xlsx is written
31 shojja.xlsx is written
ad-din.xlsx is written
aichi.xlsx is written
Al manar.xlsx is written
amz hospital.xlsx is written
Anowar khan.xlsx is written
Apollo.xlsx is written
azgor ali.xlsx is written
Bagerhat.xlsx is written
Bandarban.xlsx is written
Bangladesh Medical College Hospital.xlsx is written
Barguna.xlsx is written
Barisal.xlsx is written
BD Specialized hospital.xlsx is written
BGB Hospital.xlsx is written
Bhola.xlsx is written
BIRDEM.xlsx is written
Bogra.xlsx is written
Brahmanbaria.xlsx is written
brb hospital.xlsx is written
BSSMU.xlsx is written
Chadpur.xlsx is written
Chapai_Nawabganj.xlsx is written
Chittagong.xlsx is written
Chuadanga.xlsx is written
Comfort Nursing.xlsx is written
Coxsbazar.xlsx is written
Cumilla.xlsx is written
Dedicated Covid-19 Hospital.xlsx is written
Delta medical.xlsx is written
Dhaka central.xlsx is written
Dhaka healthcare.xlsx is written
Dhaka Mahanagar Medical College.xlsx is written
Dhaka Mahanagar Shishu Hospital.xlsx is written
Dhaka Shishu Hospital.xlsx is written
Dhaka.xlsx is written
Dinajpur.xlsx is written
dmd central.xlsx is written
Enam medical.xlsx is written
Exim bank.xlsx is written
farabi general.xlsx is written
Faridpur.xlsx is written
Feni.xlsx is written
Gaibandha.xlsx is written
Gazipur.xlsx is written
Gopalganj.xlsx is written
Govt.xlsx is written
Green Life Hospital.xlsx is written
h&h.xlsx is written
hfrc.xlsx is written
High Care Hospital.xlsx is written
Hobigonj.xlsx is written
ibn sina.xlsx is written
islami bank.xlsx is written
Jamalpur.xlsx is written
Japan BD hospital.xlsx is written
Jaypurhat.xlsx is written
Jessore.xlsx is written
Jhalkathi.xlsx is written
Jhenaidah.xlsx is written
Khagrachori.xlsx is written
Khulna.xlsx is written
Kishoregonj.xlsx is written
Kurigram.xlsx is written
Kushtia.xlsx is written
Lalmonirhat.xlsx is written
Laxmipur.xlsx is written
Life & care hospital.xlsx is written
lstm_dmc.xlsx is written
Madaripur.xlsx is written
Magura.xlsx is written
Manikganj.xlsx is written
Maulvibazar.xlsx is written
Medical college for women.xlsx is written
Meherpur.xlsx is written
Metropoliton medical.xlsx is written
monowara hospital.xlsx is written
Munsiganj.xlsx is written
Mymensingh.xlsx is written
Naogaon.xlsx is written
Narail.xlsx is written
Naraynganj.xlsx is written
Narsingdi.xlsx is written
Natore.xlsx is written
Netrokona.xlsx is written
Nilphamari.xlsx is written
Noakhali.xlsx is written
Pabna.xlsx is written
Panchagarh.xlsx is written
Patuakhali.xlsx is written
Pirojpur.xlsx is written
police hospital.xlsx is written
popular medical.xlsx is written
Rajbari.xlsx is written
Rajshahi.xlsx is written
Rangamati.xlsx is written
Rangpur.xlsx is written
Sajeda hospital.xlsx is written
salauddin hospital.xlsx is written
Satkhira.xlsx is written
Shariatpur.xlsx is written
Sherpur.xlsx is written
Shomkramok Byadhi Hospital.xlsx is written
Shommilito Shamorik Hospital,Savar.xlsx is written
Shommilito Shamorik Hospital.xlsx is written
shomorita.xlsx is written
Sirajgonj.xlsx is written
Square.xlsx is written
ssmc.xlsx is written
Sunamganj.xlsx is written
Sylhet.xlsx is written
Tangail.xlsx is written
Thakurgaon.xlsx is written
united hospital.xlsx is written
universal.xlsx is written
Uttara adhunik.xlsx is written
Uttara crescent.xlsx is written

In [38]:
# Initialize an empty numpy array with the required shape
timestep = dfs[0].shape[0]
hospitals = len(dfs)
affected_array = np.zeros((timestep, hospitals, 1))

# Populate the numpy array with the 'Affected' values from each dataframe
for i in range(hospitals):
    print(filenames[i])
    affected_array[:, i, 0] = dfs[i]['Affected'].values

# Save the numpy array to a .npy file
np.save('../../Data/BD_dengue_and_weather.npy', affected_array)

# split affected_array into training,val,test (75%,15%,10%)

train_size = int(affected_array.shape[0] * 0.75)
val_size = int(affected_array.shape[0] * 0.15)
test_size = int(affected_array.shape[0] * 0.10)

train_data = affected_array[:train_size]
val_data = affected_array[train_size:train_size+val_size]
test_data = affected_array[train_size+val_size:]

np.save('../../Data/BD_dengue_and_weather_train.npy', train_data)
np.save('../../Data/BD_dengue_and_weather_val.npy', val_data)
np.save('../../Data/BD_dengue_and_weather_test.npy', test_data)

250 shojja
31 shojja
ad-din
aichi
Al manar
amz hospital
Anowar khan
Apollo
azgor ali
Bagerhat
Bandarban
Bangladesh Medical College Hospital
Barguna
Barisal
BD Specialized hospital
BGB Hospital
Bhola
BIRDEM
Bogra
Brahmanbaria
brb hospital
BSSMU
Chadpur
Chapai_Nawabganj
Chittagong
Chuadanga
Comfort Nursing
Coxsbazar
Cumilla
Dedicated Covid-19 Hospital
Delta medical
Dhaka central
Dhaka healthcare
Dhaka Mahanagar Medical College
Dhaka Mahanagar Shishu Hospital
Dhaka Shishu Hospital
Dhaka
Dinajpur
dmd central
Enam medical
Exim bank
farabi general
Faridpur
Feni
Gaibandha
Gazipur
Gopalganj
Govt
Green Life Hospital
h&h
hfrc
High Care Hospital
Hobigonj
ibn sina
islami bank
Jamalpur
Japan BD hospital
Jaypurhat
Jessore
Jhalkathi
Jhenaidah
Khagrachori
Khulna
Kishoregonj
Kurigram
Kushtia
Lalmonirhat
Laxmipur
Life & care hospital
lstm_dmc
Madaripur
Magura
Manikganj
Maulvibazar
Medical college for women
Meherpur
Metropoliton medical
monowara hospital
Munsiganj
Mymensingh
Naogaon
Narail
Naraynganj
Narsingdi
Natore
Netrokona
Nilphamari
Noakhali
Pabna
Panchagarh
Patuakhali
Pirojpur
police hospital
popular medical
Rajbari
Rajshahi
Rangamati
Rangpur
Sajeda hospital
salauddin hospital
Satkhira
Shariatpur
Sherpur
Shomkramok Byadhi Hospital
Shommilito Shamorik Hospital,Savar
Shommilito Shamorik Hospital
shomorita
Sirajgonj
Square
ssmc
Sunamganj
Sylhet
Tangail
Thakurgaon
united hospital
universal
Uttara adhunik
Uttara crescent